language: python
python:
  - "3.5"
# command to run tests
#before-install:

before_install: 
#  - pip install pytest pytest-cov
  - pip install --upgrade termcolor
  - pip install coveralls

script: 
  - coverage run -m unittest

after_success:
  - coveralls

