language: python
python:
  - "3.5"
# command to run tests
#before-install:

install: 
  - pip install --upgrade termcolor
  - pip install coveralls
script: 
  - coverage run test.py test

after_sucess:
  - coveralls

