language: python
python:
  - "3.5"
# command to run tests
#before-install:

install: 
  - pip3 install --upgrade termcolor
  - pip3 install coveralls
script: 
  - coveralls run test_rpn.py unittest

after_sucess:
  - coveralls

